package com.qdu.student.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.qdu.student.bean.ClassExample;

public interface ClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int countByExample(ClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int deleteByExample(ClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int deleteByPrimaryKey(String csid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int insert(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int insertSelective(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    List<Class> selectByExample(ClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    Class selectByPrimaryKey(String csid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") Class record, @Param("example") ClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int updateByExample(@Param("record") Class record, @Param("example") ClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int updateByPrimaryKeySelective(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int updateByPrimaryKey(Class record);
}