package com.qdu.course.bean;

public class SourseAndCourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_ctable.s_cid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private String s_cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_ctable.sid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_ctable.cid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_ctable.state
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_ctable.score
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_ctable.s_cid
     *
     * @return the value of s_ctable.s_cid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public String getS_cid() {
        return s_cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_ctable.s_cid
     *
     * @param s_cid the value for s_ctable.s_cid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setS_cid(String s_cid) {
        this.s_cid = s_cid == null ? null : s_cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_ctable.sid
     *
     * @return the value of s_ctable.sid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_ctable.sid
     *
     * @param sid the value for s_ctable.sid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_ctable.cid
     *
     * @return the value of s_ctable.cid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_ctable.cid
     *
     * @param cid the value for s_ctable.cid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_ctable.state
     *
     * @return the value of s_ctable.state
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_ctable.state
     *
     * @param state the value for s_ctable.state
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_ctable.score
     *
     * @return the value of s_ctable.score
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_ctable.score
     *
     * @param score the value for s_ctable.score
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}