package com.qdu.course.bean;

public class SourseAndUnit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_utable.s_uid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private String s_uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_utable.sid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_utable.uid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_utable.state
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_utable.score
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_utable.s_uid
     *
     * @return the value of s_utable.s_uid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public String getS_uid() {
        return s_uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_utable.s_uid
     *
     * @param s_uid the value for s_utable.s_uid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setS_uid(String s_uid) {
        this.s_uid = s_uid == null ? null : s_uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_utable.sid
     *
     * @return the value of s_utable.sid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_utable.sid
     *
     * @param sid the value for s_utable.sid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_utable.uid
     *
     * @return the value of s_utable.uid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_utable.uid
     *
     * @param uid the value for s_utable.uid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_utable.state
     *
     * @return the value of s_utable.state
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_utable.state
     *
     * @param state the value for s_utable.state
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_utable.score
     *
     * @return the value of s_utable.score
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_utable.score
     *
     * @param score the value for s_utable.score
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}