package com.qdu.course.bean;

public class Unit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.uid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.uname
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.cid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private String cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.uid
     *
     * @return the value of unit.uid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.uid
     *
     * @param uid the value for unit.uid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.uname
     *
     * @return the value of unit.uname
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.uname
     *
     * @param uname the value for unit.uname
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.cid
     *
     * @return the value of unit.cid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.cid
     *
     * @param cid the value for unit.cid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }
}