package com.qdu.teacher.bean;

public class Exam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.eid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private String eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.ename
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.cid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.uid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.path
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.time
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private Integer time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.eid
     *
     * @return the value of exam.eid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public String getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.eid
     *
     * @param eid the value for exam.eid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setEid(String eid) {
        this.eid = eid == null ? null : eid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.ename
     *
     * @return the value of exam.ename
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.ename
     *
     * @param ename the value for exam.ename
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.cid
     *
     * @return the value of exam.cid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.cid
     *
     * @param cid the value for exam.cid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.uid
     *
     * @return the value of exam.uid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.uid
     *
     * @param uid the value for exam.uid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.path
     *
     * @return the value of exam.path
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.path
     *
     * @param path the value for exam.path
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.time
     *
     * @return the value of exam.time
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.time
     *
     * @param time the value for exam.time
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setTime(Integer time) {
        this.time = time;
    }
}