package com.qdu.teacher.bean;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private String tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tname
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private String tname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tpassword
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    private String tpassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tid
     *
     * @return the value of teacher.tid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tid
     *
     * @param tid the value for teacher.tid
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tname
     *
     * @return the value of teacher.tname
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tname
     *
     * @param tname the value for teacher.tname
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tpassword
     *
     * @return the value of teacher.tpassword
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public String getTpassword() {
        return tpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tpassword
     *
     * @param tpassword the value for teacher.tpassword
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    public void setTpassword(String tpassword) {
        this.tpassword = tpassword == null ? null : tpassword.trim();
    }
}