package com.qdu.student.bean;

public class Class {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.csid
     *
     * @mbggenerated Tue Nov 28 22:09:34 CST 2017
     */
    private String csid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class.csname
     *
     * @mbggenerated Tue Nov 28 22:09:34 CST 2017
     */
    private String csname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.csid
     *
     * @return the value of class.csid
     *
     * @mbggenerated Tue Nov 28 22:09:34 CST 2017
     */
    public String getCsid() {
        return csid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.csid
     *
     * @param csid the value for class.csid
     *
     * @mbggenerated Tue Nov 28 22:09:34 CST 2017
     */
    public void setCsid(String csid) {
        this.csid = csid == null ? null : csid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class.csname
     *
     * @return the value of class.csname
     *
     * @mbggenerated Tue Nov 28 22:09:34 CST 2017
     */
    public String getCsname() {
        return csname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class.csname
     *
     * @param csname the value for class.csname
     *
     * @mbggenerated Tue Nov 28 22:09:34 CST 2017
     */
    public void setCsname(String csname) {
        this.csname = csname == null ? null : csname.trim();
    }
}