package com.lulech.pojo;
// Generated 2017-6-16 0:05:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Chapters generated by hbm2java
 */
public class Chapters  implements java.io.Serializable {

     private String chapterId;
     private Courses courses;
     private String title;
     private String chapter;
     private String content;
     private Set examses = new HashSet(0);

    public Chapters() {
    }

	
    public Chapters(String chapterId) {
        this.chapterId = chapterId;
    }
    public Chapters(String chapterId, Courses courses, String title, String chapter, String content, Set examses) {
       this.chapterId = chapterId;
       this.courses = courses;
       this.title = title;
       this.chapter = chapter;
       this.content = content;
       this.examses = examses;
    }
   
    public String getChapterId() {
        return this.chapterId;
    }
    
    public void setChapterId(String chapterId) {
        this.chapterId = chapterId;
    }
    public Courses getCourses() {
        return this.courses;
    }
    
    public void setCourses(Courses courses) {
        this.courses = courses;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getChapter() {
        return this.chapter;
    }
    
    public void setChapter(String chapter) {
        this.chapter = chapter;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Set getExamses() {
        return this.examses;
    }
    
    public void setExamses(Set examses) {
        this.examses = examses;
    }
}


