package com.lulech.pojo;
// Generated 2017-6-16 0:05:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Courses generated by hbm2java
 */
public class Courses  implements java.io.Serializable {


     private String courseId;
     private String title;
     private Set chapterses = new HashSet(0);
     private Set classeses = new HashSet(0);

    public Courses() {
    }
    
    public Courses(String courseId, String title) {
        this.courseId = courseId;
        this.title = title;
    }
    
    public Courses(String courseId, String title, Set chapterses, Set classeses) {
       this.courseId = courseId;
       this.title = title;
       this.chapterses = chapterses;
       this.classeses = classeses;
    }
   
    public String getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(String courseId) {
        this.courseId = courseId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Set getChapterses() {
        return this.chapterses;
    }
    
    public void setChapterses(Set chapterses) {
        this.chapterses = chapterses;
    }
    public Set getClasseses() {
        return this.classeses;
    }
    
    public void setClasseses(Set classeses) {
        this.classeses = classeses;
    }




}


