package com.lulech.pojo;
// Generated 2017-6-16 0:05:20 by Hibernate Tools 4.3.1



/**
 * CurriculaVariable generated by hbm2java
 */
public class CurriculaVariable  implements java.io.Serializable {


     private String cvId;
     private Classes classes;
     private Students students;

    public CurriculaVariable() {
    }

	
    public CurriculaVariable(String cvId) {
        this.cvId = cvId;
    }
    public CurriculaVariable(String cvId, Classes classes, Students students) {
       this.cvId = cvId;
       this.classes = classes;
       this.students = students;
    }
   
    public String getCvId() {
        return this.cvId;
    }
    
    public void setCvId(String cvId) {
        this.cvId = cvId;
    }
    public Classes getClasses() {
        return this.classes;
    }
    
    public void setClasses(Classes classes) {
        this.classes = classes;
    }
    public Students getStudents() {
        return this.students;
    }
    
    public void setStudents(Students students) {
        this.students = students;
    }
}

