package com.lulech.pojo;
import java.util.HashSet;
import java.util.Set;

/**
 * Exams generated by hbm2java
 */
public class Exams  implements java.io.Serializable {


     private String ECode;
     private Chapters chapters;
     private String filepath;
     private Integer ETime;
     private Set scoreses = new HashSet(0);

    public Exams() {
    }

	
    public Exams(String ECode) {
        this.ECode = ECode;
    }
    public Exams(String ECode, Chapters chapters, String filepath, Integer ETime, Set scoreses) {
       this.ECode = ECode;
       this.chapters = chapters;
       this.filepath = filepath;
       this.ETime = ETime;
       this.scoreses = scoreses;
    }
   
    public String getECode() {
        return this.ECode;
    }
    
    public void setECode(String ECode) {
        this.ECode = ECode;
    }
    public Chapters getChapters() {
        return this.chapters;
    }
    
    public void setChapters(Chapters chapters) {
        this.chapters = chapters;
    }
    public String getFilepath() {
        return this.filepath;
    }
    
    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }
    public Integer getETime() {
        return this.ETime;
    }
    
    public void setETime(Integer ETime) {
        this.ETime = ETime;
    }
    public Set getScoreses() {
        return this.scoreses;
    }
    
    public void setScoreses(Set scoreses) {
        this.scoreses = scoreses;
    }
}

