package com.lulech.pojo;
// Generated 2017-6-16 0:05:20 by Hibernate Tools 4.3.1



/**
 * Scores generated by hbm2java
 */
public class Scores  implements java.io.Serializable {


     private String scoreId;
     private Exams exams;
     private Students students;
     private Integer score;

    public Scores() {
    }

	
    public Scores(String scoreId) {
        this.scoreId = scoreId;
    }
    public Scores(String scoreId, Exams exams, Students students, Integer score) {
       this.scoreId = scoreId;
       this.exams = exams;
       this.students = students;
       this.score = score;
    }
   
    public String getScoreId() {
        return this.scoreId;
    }
    
    public void setScoreId(String scoreId) {
        this.scoreId = scoreId;
    }
    public Exams getExams() {
        return this.exams;
    }
    
    public void setExams(Exams exams) {
        this.exams = exams;
    }
    public Students getStudents() {
        return this.students;
    }
    
    public void setStudents(Students students) {
        this.students = students;
    }
    public Integer getScore() {
        return this.score;
    }
    
    public void setScore(Integer score) {
        this.score = score;
    }




}


