package com.lulech.pojo;
// Generated 2017-6-16 0:05:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Students generated by hbm2java
 */
public class Students  implements java.io.Serializable {


     private String stuId;
     private String cnName;
     private String enName;
     private String profilePath;
     private String spassword;
     private Set curriculaVariables = new HashSet(0);
     private Set scoreses = new HashSet(0);

    public Students() {
    }

	
    public Students(String stuId, String cnName, String enName, String spassword) {
        this.stuId = stuId;
        this.cnName = cnName;
        this.enName = enName;
        this.spassword = spassword;
    }
    public Students(String stuId, String cnName, String enName, String profilePath, String spassword, Set curriculaVariables, Set scoreses) {
       this.stuId = stuId;
       this.cnName = cnName;
       this.enName = enName;
       this.profilePath = profilePath;
       this.spassword = spassword;
       this.curriculaVariables = curriculaVariables;
       this.scoreses = scoreses;
    }
   
    public String getStuId() {
        return this.stuId;
    }
    
    public void setStuId(String stuId) {
        this.stuId = stuId;
    }
    public String getCnName() {
        return this.cnName;
    }
    
    public void setCnName(String cnName) {
        this.cnName = cnName;
    }
    public String getEnName() {
        return this.enName;
    }
    
    public void setEnName(String enName) {
        this.enName = enName;
    }
    public String getProfilePath() {
        return this.profilePath;
    }
    
    public void setProfilePath(String profilePath) {
        this.profilePath = profilePath;
    }
    public String getSpassword() {
        return this.spassword;
    }
    
    public void setSpassword(String spassword) {
        this.spassword = spassword;
    }
    public Set getCurriculaVariables() {
        return this.curriculaVariables;
    }
    
    public void setCurriculaVariables(Set curriculaVariables) {
        this.curriculaVariables = curriculaVariables;
    }
    public Set getScoreses() {
        return this.scoreses;
    }
    
    public void setScoreses(Set scoreses) {
        this.scoreses = scoreses;
    }




}


