package com.lulech.pojo;
// Generated 2017-6-16 0:05:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Teachers generated by hbm2java
 */
public class Teachers  implements java.io.Serializable {


     private String teaId;
     private String cnName;
     private String enName;
     private String profilePath;
     private String tpassword;
     private Set classeses = new HashSet(0);

    public Teachers() {
    }

	
    public Teachers(String teaId, String cnName, String enName, String tpassword) {
        this.teaId = teaId;
        this.cnName = cnName;
        this.enName = enName;
        this.tpassword = tpassword;
    }
    public Teachers(String teaId, String cnName, String enName, String profilePath, String tpassword, Set classeses) {
       this.teaId = teaId;
       this.cnName = cnName;
       this.enName = enName;
       this.profilePath = profilePath;
       this.tpassword = tpassword;
       this.classeses = classeses;
    }
   
    public String getTeaId() {
        return this.teaId;
    }
    
    public void setTeaId(String teaId) {
        this.teaId = teaId;
    }
    public String getCnName() {
        return this.cnName;
    }
    
    public void setCnName(String cnName) {
        this.cnName = cnName;
    }
    public String getEnName() {
        return this.enName;
    }
    
    public void setEnName(String enName) {
        this.enName = enName;
    }
    public String getProfilePath() {
        return this.profilePath;
    }
    
    public void setProfilePath(String profilePath) {
        this.profilePath = profilePath;
    }
    public String getTpassword() {
        return this.tpassword;
    }
    
    public void setTpassword(String tpassword) {
        this.tpassword = tpassword;
    }
    public Set getClasseses() {
        return this.classeses;
    }
    
    public void setClasseses(Set classeses) {
        this.classeses = classeses;
    }




}


