package com.qdu.course.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.qdu.course.bean.SourseAndUnit;
import com.qdu.course.bean.SourseAndUnitExample;

public interface SourseAndUnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_utable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int countByExample(SourseAndUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_utable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int deleteByExample(SourseAndUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_utable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int deleteByPrimaryKey(String s_uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_utable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int insert(SourseAndUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_utable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int insertSelective(SourseAndUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_utable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    List<SourseAndUnit> selectByExample(SourseAndUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_utable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    SourseAndUnit selectByPrimaryKey(String s_uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_utable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") SourseAndUnit record, @Param("example") SourseAndUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_utable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int updateByExample(@Param("record") SourseAndUnit record, @Param("example") SourseAndUnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_utable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int updateByPrimaryKeySelective(SourseAndUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_utable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int updateByPrimaryKey(SourseAndUnit record);
}