package com.qdu.course.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.qdu.course.bean.SourseAndCourse;
import com.qdu.course.bean.SourseAndCourseExample;

public interface SourseAndCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_ctable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int countByExample(SourseAndCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_ctable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int deleteByExample(SourseAndCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_ctable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int deleteByPrimaryKey(String s_cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_ctable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int insert(SourseAndCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_ctable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int insertSelective(SourseAndCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_ctable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    List<SourseAndCourse> selectByExample(SourseAndCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_ctable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    SourseAndCourse selectByPrimaryKey(String s_cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_ctable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") SourseAndCourse record, @Param("example") SourseAndCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_ctable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int updateByExample(@Param("record") SourseAndCourse record, @Param("example") SourseAndCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_ctable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int updateByPrimaryKeySelective(SourseAndCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_ctable
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int updateByPrimaryKey(SourseAndCourse record);
}