package com.qdu.course.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.qdu.course.bean.Unit;
import com.qdu.course.bean.UnitExample;

public interface UnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int countByExample(UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int deleteByExample(UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int insert(Unit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int insertSelective(Unit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    List<Unit> selectByExample(UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    Unit selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") Unit record, @Param("example") UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int updateByExample(@Param("record") Unit record, @Param("example") UnitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int updateByPrimaryKeySelective(Unit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated Tue Nov 28 21:50:35 CST 2017
     */
    int updateByPrimaryKey(Unit record);
}